[project]
name = "sise-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "helium>=5.1.0",
    "polars>=1.17.1",
]

[tool.ruff]
ignore = ["F405", "F403"]